/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 javascript.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/javascript.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[0.438, -0.013, 0.017]} rotation={[1.574, 0, -3.076]} scale={[1.376, 1.002, 1]} />
    </group>
  )
}

useGLTF.preload('/javascript.glb')
